version: '3.6'

services:
  db:
    image: postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8003
    volumes:
      - .:/code
    ports:
      - "8003:8003"
    depends_on:
      - db
    entrypoint: /entrypoint.sh
  redis:
    image: "redis:alpine"
  celery:
    build: .
    command: bash -c "celery -A training_server.celery worker -l DEBUG -E"
    volumes:
    - .:/code
    depends_on:
    - db
    - redis